name: Hyperlane
contracts:
- name: Mailbox
  handler: src/EventHandlers.ts
  events:
  - event: DefaultHookSet(address indexed hook)
  - event: Dispatch(address indexed sender, uint32 indexed destination, bytes32 indexed recipient, bytes message)
  - event: DispatchId(bytes32 indexed messageId)
  - event: Initialized(uint8 version)
  - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
  - event: Process(uint32 indexed origin, bytes32 indexed sender, address indexed recipient)
  - event: ProcessId(bytes32 indexed messageId)
  - event: RequiredHookSet(address indexed hook)
networks:
- id: 1
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0xc005dc82818d67AF737725bD4bf75435d065D239
- id: 10
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0xd4C1905BB1D26BC93DAC913e13CaCC278CdCC80D
- id: 56
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0x2971b9Aec44bE4eb673DF1B88cDB57b96eefe8a4
- id: 100
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0xaD09d78f4c6b9dA2Ae82b1D34107802d380Bb74f
- id: 137
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0x5d934f4e2f797775e53561bB72aca21ba36B96BB
- id: 1101
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0x3a464f746D23Ab22155710f44dB16dcA53e0775E
- id: 1284
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0x094d03E751f49908080EFf000Dd6FD177fd44CC3
- id: 8453
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0xeA87ae93Fa0019a82A727bfd3eBd1cFCa8f64f1D
- id: 42161
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0x979Ca5202784112f4738403dBec5D0F3B9daabB9
- id: 42220
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0x50da3B3907A08a24fe4999F4Dcf337E8dC7954bb
- id: 43114
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0xFf06aFcaABaDDd1fb08371f9ccA15D73D51FeBD6
- id: 534352
  start_block: 0
  contracts:
  - name: Mailbox
    address:
    - 0x2f2aFaE1139Ce54feFC03593FeE8AB2aDF4a85A7
